-- HOSPITAL ADMINISTRATION SYSTEM (MySQL) -- 

-- DATABASE CREATION --  

CREATE DATABASE HOSPITAL_DB;
USE HOSPITAL_DB;

-- TABLE DESIGN -- 

CREATE TABLE DEPARTMENTS(DEPARTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,DEPARTMENT_NAME VARCHAR(50));
CREATE TABLE DOCTORS(DOCTOR_ID INT PRIMARY KEY AUTO_INCREMENT,DOCTOR_NAME VARCHAR(50),SPECIALIZATION VARCHAR(100),DEPARTMENT_ID INT, PHONE VARCHAR(50),
								FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID));
CREATE TABLE PATIENTS(PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,PATIENT_NAME VARCHAR(50),AGE INT,GENDER ENUM('M','F'),PHONE VARCHAR(50));
CREATE TABLE APPOINTMENTS (APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,PATIENT_ID INT,DOCTOR_ID INT,APPOINTMENT_DATE DATE,
								APPOINTMENT_TIME TIME,STATUS VARCHAR(50), FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
								FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID));
CREATE TABLE BILLING(BILL_ID INT PRIMARY KEY AUTO_INCREMENT,PATIENT_ID INT,AMOUNT INT,BILL_DATE DATE,PAYMENT_STATUS VARCHAR(50),
                                FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID));
                                
-- DATA IMPORT -- 

INSERT INTO DEPARTMENTS(DEPARTMENT_NAME) VALUES('CARDIOLOGY'),('NEUROLOGY'),('ORTHOPEDICS'),('GENERAL MEDICINE');
INSERT INTO DOCTORS(DOCTOR_NAME,SPECIALIZATION,DEPARTMENT_ID,PHONE) VALUES('DR.ANIL KUMAR','CARDIOLOGIST',1,9876543210),
													('DR.MEERA NAIR','NEUROLOGIST',2,9876543222),('DR.JOHN THOMAS','ORTHOPEDIC',3,9876543233);
INSERT INTO PATIENTS(PATIENT_NAME,AGE,GENDER,PHONE) VALUES('RAHUL MENON',35,'M',9123456780),('ANJALI DEVI',28,'F',9123456791),
													('SURESH KUMAR',52,'M',9123456792);
INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE,APPOINTMENT_TIME,STATUS)VALUES(1,1,'2025-01-05','10:30','COMPLETED'),
                                                    (2,2,'2025-01-06','11:00','PENDING'),(3,1,'2025-01-06','12:00','CANCELLED');
INSERT INTO BILLING(PATIENT_ID,AMOUNT,BILL_DATE,PAYMENT_STATUS) VALUES(1,2500,'2025-01-05','PAID'),(2,4000,'2025-01-06','UNPAID'),
													(3,1500,'2025-01-06','PAID');
SELECT * FROM DEPARTMENTS;
SELECT * FROM DOCTORS;
SELECT * FROM PATIENTS;
SELECT * FROM APPOINTMENTS;
SELECT * FROM BILLING;	

-- BUSINESS REQUIREMENT QUERIES -- 

SELECT P.PATIENT_NAME,D.DOCTOR_NAME,D.SPECIALIZATION FROM PATIENTS P JOIN APPOINTMENTS A ON P.PATIENT_ID=A.PATIENT_ID JOIN DOCTORS D ON
                                                                            A.DOCTOR_ID=D.DOCTOR_ID;
SELECT P.PATIENT_ID,P.PATIENT_NAME,D.DOCTOR_NAME,A.APPOINTMENT_DATE,A.APPOINTMENT_TIME FROM PATIENTS P JOIN APPOINTMENTS A ON 
								P.PATIENT_ID=A.PATIENT_ID JOIN DOCTORS D ON A.DOCTOR_ID=D.DOCTOR_ID WHERE APPOINTMENT_DATE=CURDATE();
SELECT D.DOCTOR_NAME, DT.DEPARTMENT_NAME FROM DOCTORS D JOIN DEPARTMENTS DT ON D.DEPARTMENT_ID=DT.DEPARTMENT_ID;
SELECT SUM(AMOUNT) AS TOTAL_REVENUE FROM BILLING WHERE PAYMENT_STATUS="PAID";
SELECT B.PATIENT_ID,P.PATIENT_NAME,B.PAYMENT_STATUS FROM BILLING B JOIN PATIENTS P ON 
                                                            B.PATIENT_ID=P.PATIENT_ID WHERE B.PAYMENT_STATUS='UNPAID';
SELECT D.DOCTOR_NAME,COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS FROM DOCTORS D JOIN APPOINTMENTS A ON 
                                                            D.DOCTOR_ID=A.DOCTOR_ID GROUP BY D.DOCTOR_NAME;
SELECT DT.DEPARTMENT_NAME,COUNT(D.DOCTOR_ID) AS NO_OF_DOCTORS FROM DOCTORS D JOIN DEPARTMENTS DT ON 
                                                            D.DEPARTMENT_ID=DT.DEPARTMENT_ID GROUP BY DT.DEPARTMENT_NAME;
                                                            
-- UPDATE & DELETE OPERATIONS --

UPDATE APPOINTMENTS SET STATUS='COMPLETED' WHERE STATUS='PENDING';
SELECT * FROM APPOINTMENTS;
DELETE FROM APPOINTMENTS WHERE STATUS='CANCELLED';
SELECT * FROM APPOINTMENTS;
UPDATE BILLING SET PAYMENT_STATUS='PAID' WHERE BILL_ID=2;
SELECT * FROM BILLING;

-- ADVANCED SQL --  

SELECT * FROM PATIENTS P JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID WHERE B.AMOUNT > (SELECT AVG(AMOUNT) FROM BILLING);
SELECT D.DOCTOR_NAME,COUNT(A.APPOINTMENT_ID) AS TOTAL_NO_OF_APPOINTMENTS FROM DOCTORS D JOIN APPOINTMENTS A ON D.DOCTOR_ID=A.DOCTOR_ID 
                                    GROUP BY D.DOCTOR_NAME HAVING COUNT(A.APPOINTMENT_ID)>1;
SELECT P.PATIENT_NAME, B.AMOUNT AS MAXIMUM_BILL_AMOUNT FROM PATIENTS P JOIN BILLING B ON 
	P.PATIENT_ID=B.PATIENT_ID WHERE B.PAYMENT_STATUS='PAID' AND B.AMOUNT=(SELECT MAX(AMOUNT) FROM BILLING WHERE PAYMENT_STATUS ='PAID');
                                                                   



											